import type {
  AWBSerialRange,
  AppUser,
  Bill,
  Company,
  CourierBrand,
  CourierPickup,
  CourierTariff,
  Customer,
  DesignOrder,
  DesignPricingMaster,
  Expense,
  GeneralProduct,
  Invoice,
  PurchaseInvoice,
  ServiceProduct,
  Vendor,
  XeroxProduct,
} from "../types";
import {
  getAWBSerials,
  getBills,
  getCompanies,
  getCustomers,
  getDesignOrders,
  getDesignPricing,
  getExpenses,
  getInvoices,
  getPickups,
  getProducts,
  getPurchaseInvoices,
  getSettings,
  getTariffs,
  getUsers,
  getVendors,
  setAWBSerials,
  setBills,
  setCompanies,
  setCustomers,
  setDesignOrders,
  setDesignPricing,
  setExpenses,
  setInvoices,
  setPickups,
  setProducts,
  setPurchaseInvoices,
  setSettings,
  setTariffs,
  setUsers,
  setVendors,
} from "./storage";

const hashPassword = (pwd: string): string => btoa(pwd);

/** Returns a date string offset from today (negative = past) */
const daysAgo = (n: number): string => {
  const d = new Date();
  d.setDate(d.getDate() - n);
  return d.toISOString().split("T")[0];
};

export const seedInitialData = (): void => {
  const companyId = "company_01";

  // Always ensure default users exist (even if companies were already seeded)
  const existingUsers = getUsers();
  const adminExists = existingUsers.some((u) => u.username === "admin");
  const operatorExists = existingUsers.some((u) => u.username === "operator");

  if (!adminExists || !operatorExists) {
    const baseUsers = existingUsers.filter(
      (u) => u.username !== "admin" && u.username !== "operator",
    );
    const defaultUsers: AppUser[] = [...baseUsers];
    if (!adminExists) {
      defaultUsers.unshift({
        id: "user_admin_01",
        name: "Admin User",
        username: "admin",
        passwordHash: hashPassword("admin123"),
        role: "admin",
        companyIds: [companyId],
      });
    }
    if (!operatorExists) {
      defaultUsers.push({
        id: "user_op_01",
        name: "Operator User",
        username: "operator",
        passwordHash: hashPassword("op123"),
        role: "operator",
        companyIds: [companyId],
      });
    }
    setUsers(defaultUsers);
  }

  // Only seed companies and related data if no companies exist
  const companies = getCompanies();

  // If companies already exist, ensure SKS Global Express own-brand is present in each company
  if (companies.length > 0) {
    for (const company of companies) {
      const cid = company.id;
      const existingProds = getProducts(cid);
      const hasSKSOwnBrand = existingProds.some(
        (p) =>
          p.type === "courier_awb" && (p as CourierBrand).isOwnBrand === true,
      );
      if (!hasSKSOwnBrand) {
        const sksOwnBrand: CourierBrand = {
          id: `brand_sks_own_${cid}`,
          companyId: cid,
          type: "courier_awb",
          brandName: "SKS Global Express",
          brandSubtitle: "Domestic and International",
          productType: "Own Brand Courier",
          serviceModes: ["Domestic", "International"],
          transportModes: "Both",
          serialLogic: "own_brand_auto",
          isOwnBrand: true,
          sellingPrice: 80,
          gstRate: 18,
          isActive: true,
        };
        setProducts(cid, [...existingProds, sksOwnBrand]);
      }
    }
    return;
  }

  // ─── Company ─────────────────────────────────────────────────────────────────
  const company: Company = {
    id: companyId,
    name: "SKS Global Export",
    address: "123 Export House, Anna Salai, Chennai - 600001",
    gstin: "33AABCS1234A1Z5",
    phone: "9876543210",
    email: "info@sksglobalexport.com",
    invoicePrefix: "GST/",
    invoiceSeq: 1,
    nonGstInvoicePrefix: "INV/",
    nonGstInvoiceSeq: 1,
    billPrefix: "BILL/",
    billSeq: 1,
    state: "Tamil Nadu",
    pincode: "600001",
    bankName: "HDFC Bank",
    bankAccount: "50100123456789",
    bankIfsc: "HDFC0001234",
    bankBranch: "Anna Salai Branch",
  };
  setCompanies([company]);

  // ─── Products ────────────────────────────────────────────────────────────────
  const existingProducts = getProducts(companyId);
  if (existingProducts.length === 0) {
    const paperProduct: GeneralProduct = {
      id: "prod_paper_01",
      companyId,
      type: "general",
      name: "A4 Paper",
      category: "Stationery",
      unit: "Ream",
      subUnit1: { name: "Sheet", conversionRate: 500 },
      sellingPrice: 280,
      purchasePrice: 220,
      gstRate: 12,
      hsnCode: "4802",
      currentStock: 100,
      minStockAlert: 20,
      isActive: true,
    };

    const inkProduct: GeneralProduct = {
      id: "prod_ink_01",
      companyId,
      type: "general",
      name: "Blue Ink Cartridge",
      category: "Stationery",
      unit: "Piece",
      sellingPrice: 480,
      purchasePrice: 350,
      gstRate: 18,
      hsnCode: "8443",
      currentStock: 20,
      minStockAlert: 5,
      isActive: true,
    };

    const envelopeProduct: GeneralProduct = {
      id: "prod_env_01",
      companyId,
      type: "general",
      name: "A4 Envelope",
      category: "Stationery",
      unit: "Pack",
      subUnit1: { name: "Piece", conversionRate: 50 },
      sellingPrice: 120,
      purchasePrice: 80,
      gstRate: 12,
      hsnCode: "4817",
      currentStock: 50,
      minStockAlert: 10,
      isActive: true,
    };

    const bubbleWrapProduct: GeneralProduct = {
      id: "prod_bubble_01",
      companyId,
      type: "general",
      name: "Bubble Wrap Roll",
      category: "Packaging",
      unit: "Roll",
      subUnit1: { name: "Meter", conversionRate: 50 },
      sellingPrice: 350,
      purchasePrice: 250,
      gstRate: 18,
      hsnCode: "3926",
      currentStock: 30,
      minStockAlert: 5,
      isActive: true,
    };

    const tapeProduct: GeneralProduct = {
      id: "prod_tape_01",
      companyId,
      type: "general",
      name: "Packing Tape 2 inch",
      category: "Packaging",
      unit: "Piece",
      sellingPrice: 45,
      purchasePrice: 30,
      gstRate: 18,
      hsnCode: "3919",
      currentStock: 80,
      minStockAlert: 15,
      isActive: true,
    };

    const xeroxProduct: XeroxProduct = {
      id: "prod_xerox_01",
      companyId,
      type: "xerox",
      name: "Xerox A4",
      paperProductId: "prod_paper_01",
      inkChargePerPage: 0.3,
      serviceChargePerPage: 0.2,
      pricePerPage: 1.0,
      gstRate: 18,
      isActive: true,
    };

    const colorXerox: XeroxProduct = {
      id: "prod_xerox_color_01",
      companyId,
      type: "xerox",
      name: "Color Xerox A4",
      paperProductId: "prod_paper_01",
      inkChargePerPage: 3.0,
      serviceChargePerPage: 0.5,
      pricePerPage: 8.0,
      gstRate: 18,
      isActive: true,
    };

    const scanService: ServiceProduct = {
      id: "prod_scan_01",
      companyId,
      type: "service",
      name: "Document Scanning",
      description: "Scanning documents to PDF format",
      price: 10,
      gstRate: 18,
      sacCode: "998319",
      isActive: true,
    };

    const printService: ServiceProduct = {
      id: "prod_print_01",
      companyId,
      type: "service",
      name: "Color Printout",
      description: "High quality color printing",
      price: 15,
      gstRate: 18,
      sacCode: "998319",
      isActive: true,
    };

    const laminationService: ServiceProduct = {
      id: "prod_lam_01",
      companyId,
      type: "service",
      name: "Lamination A4",
      description: "Hot lamination for A4 documents",
      price: 20,
      gstRate: 18,
      sacCode: "998319",
      isActive: true,
    };

    const dtdcBrand: CourierBrand = {
      id: "brand_dtdc_01",
      companyId,
      type: "courier_awb",
      brandName: "DTDC",
      productType: "Courier",
      serviceModes: ["Air", "Surface", "GEC"],
      transportModes: "Both",
      serialLogic: "sequential",
      sellingPrice: 85,
      gstRate: 18,
      isActive: true,
    };

    const bluedartBrand: CourierBrand = {
      id: "brand_bluedart_01",
      companyId,
      type: "courier_awb",
      brandName: "BlueDart",
      productType: "Express Courier",
      serviceModes: ["Air", "Surface"],
      transportModes: "Both",
      serialLogic: "custom_gap",
      serialGap: 11,
      sellingPrice: 120,
      gstRate: 18,
      isActive: true,
    };

    const delhiverBrand: CourierBrand = {
      id: "brand_delhivery_01",
      companyId,
      type: "courier_awb",
      brandName: "Delhivery",
      productType: "Courier",
      serviceModes: ["Surface", "Air"],
      transportModes: "Both",
      serialLogic: "sequential_prefix_first",
      serialPrefix: "DL",
      prefixPosition: "first",
      sellingPrice: 75,
      gstRate: 18,
      isActive: true,
    };

    const sksOwnBrand: CourierBrand = {
      id: "brand_sks_own_01",
      companyId,
      type: "courier_awb",
      brandName: "SKS Global Express",
      brandSubtitle: "Domestic and International",
      productType: "Own Brand Courier",
      serviceModes: ["Domestic", "International"],
      transportModes: "Both",
      serialLogic: "own_brand_auto",
      isOwnBrand: true,
      sellingPrice: 80,
      gstRate: 18,
      isActive: true,
    };

    setProducts(companyId, [
      paperProduct,
      inkProduct,
      envelopeProduct,
      bubbleWrapProduct,
      tapeProduct,
      xeroxProduct,
      colorXerox,
      scanService,
      printService,
      laminationService,
      dtdcBrand,
      bluedartBrand,
      delhiverBrand,
      sksOwnBrand,
    ]);

    // Seed AWB serials
    const dtdcSerials: AWBSerialRange = {
      id: "awb_dtdc_01",
      companyId,
      brandId: "brand_dtdc_01",
      brandName: "DTDC",
      fromSerial: "D100001",
      toSerial: "D100200",
      quantity: 200,
      purchaseDate: daysAgo(10),
      usedSerials: [
        "D100001",
        "D100002",
        "D100003",
        "D100004",
        "D100005",
        "D100006",
        "D100007",
      ],
      availableSerials: Array.from({ length: 193 }, (_, i) => `D${100008 + i}`),
    };

    const bluedartSerials: AWBSerialRange = {
      id: "awb_bluedart_01",
      companyId,
      brandId: "brand_bluedart_01",
      brandName: "BlueDart",
      fromSerial: "48064699185",
      toSerial: "48064699900",
      quantity: 64,
      purchaseDate: daysAgo(15),
      usedSerials: ["48064699185", "48064699196"],
      availableSerials: (() => {
        const nums = [
          48064699200, 48064699211, 48064699222, 48064699233, 48064699244,
          48064699255, 48064699266, 48064699270,
        ];
        return nums.map(String);
      })(),
    };

    const existingSerials = getAWBSerials(companyId);
    if (existingSerials.length === 0) {
      setAWBSerials(companyId, [dtdcSerials, bluedartSerials]);
    }
  }

  // ─── Customers ───────────────────────────────────────────────────────────────
  const existingCustomers = getCustomers(companyId);
  if (existingCustomers.length === 0) {
    const customers: Customer[] = [
      {
        id: "cust_01",
        companyId,
        customerType: "registered",
        name: "Rajesh Kumar",
        phone: "9876500001",
        email: "rajesh@example.com",
        address: "45 Gandhi Nagar, Chennai - 600020",
        totalPurchases: 18500,
        isActive: true,
      },
      {
        id: "cust_02",
        companyId,
        customerType: "registered",
        name: "Priya Traders",
        phone: "9876500002",
        email: "priya@priyatraders.com",
        address: "78 Commercial Street, Chennai - 600003",
        gstin: "33BBBCS5678B1Z5",
        totalPurchases: 42800,
        isActive: true,
      },
      {
        id: "cust_03",
        companyId,
        customerType: "registered",
        name: "Suresh Electronics",
        phone: "9876500003",
        email: "suresh@surelectronics.com",
        address: "12 Tech Park, Chennai - 600028",
        totalPurchases: 28200,
        isActive: true,
      },
      {
        id: "cust_04",
        companyId,
        customerType: "registered",
        name: "Meena Fashions",
        phone: "9876500004",
        email: "meena@meenafashions.com",
        address: "33 T Nagar, Chennai - 600017",
        gstin: "33DDDMF7890D1Z9",
        totalPurchases: 15600,
        isActive: true,
      },
      {
        id: "cust_05",
        companyId,
        customerType: "registered",
        name: "Arjun Logistics",
        phone: "9876500005",
        email: "arjun@arjunlogistics.in",
        address: "7 Industrial Estate, Chennai - 600096",
        gstin: "33EEEALS1122E1Z3",
        totalPurchases: 65000,
        isActive: true,
      },
      {
        id: "cust_06",
        companyId,
        customerType: "registered",
        name: "Kavitha Pharma",
        phone: "9876500006",
        email: "kavitha@kavithapharma.com",
        address: "22 Ambattur Industrial, Chennai - 600058",
        totalPurchases: 9200,
        isActive: true,
      },
      {
        id: "cust_07",
        companyId,
        customerType: "registered",
        name: "Sri Balaji Traders",
        phone: "9876500007",
        address: "55 Kilpauk Garden, Chennai - 600010",
        totalPurchases: 11400,
        isActive: true,
      },
      {
        id: "cust_walk_01",
        companyId,
        customerType: "walking",
        name: "Walking Customer",
        phone: "0000000000",
        totalPurchases: 0,
        isActive: true,
      },
    ];
    setCustomers(companyId, customers);
  }

  // ─── Vendors ─────────────────────────────────────────────────────────────────
  const existingVendors = getVendors(companyId);
  if (existingVendors.length === 0) {
    const vendors: Vendor[] = [
      {
        id: "vend_01",
        companyId,
        name: "Chennai Paper Mart",
        phone: "9876600001",
        email: "purchase@chennaipapermart.com",
        address: "55 Warehouse Road, Chennai - 600010",
        gstin: "33CCCPA1234C1Z5",
        totalPurchases: 75000,
        isActive: true,
      },
      {
        id: "vend_02",
        companyId,
        name: "DTDC Franchise Hub",
        phone: "9876600002",
        address: "DTDC Hub, Guindy, Chennai - 600030",
        totalPurchases: 38000,
        isActive: true,
      },
      {
        id: "vend_03",
        companyId,
        name: "BlueDart Distribution",
        phone: "9876600003",
        address: "BlueDart Center, Perungudi, Chennai - 600032",
        totalPurchases: 42000,
        isActive: true,
      },
      {
        id: "vend_04",
        companyId,
        name: "Delhivery Pickup Partner",
        phone: "9876600004",
        address: "Delhivery WH, Ambattur, Chennai - 600058",
        totalPurchases: 18500,
        isActive: true,
      },
      {
        id: "vend_05",
        companyId,
        name: "Packcraft Supplies",
        phone: "9876600005",
        email: "orders@packcraft.com",
        address: "12 Packaging Lane, Chennai - 600016",
        gstin: "33PPPCS9988P1Z2",
        totalPurchases: 22000,
        isActive: true,
      },
    ];
    setVendors(companyId, vendors);
  }

  // ─── Bills ───────────────────────────────────────────────────────────────────
  const existingBills = getBills(companyId);
  if (existingBills.length === 0) {
    const bills: Bill[] = [
      // Today's bills
      {
        id: "bill_01",
        companyId,
        billNo: "BILL/001",
        customerId: "cust_01",
        customerName: "Rajesh Kumar",
        customerType: "registered",
        date: daysAgo(0),
        items: [
          {
            id: "bi_01_1",
            productId: "prod_paper_01",
            productType: "general",
            productName: "A4 Paper",
            quantity: 2,
            unit: "Ream",
            unitPrice: 280,
            totalPrice: 560,
            gstRate: 12,
          },
          {
            id: "bi_01_2",
            productId: "prod_scan_01",
            productType: "service",
            productName: "Document Scanning",
            description: "10 pages A4 scanning to PDF",
            quantity: 10,
            unit: "Page",
            unitPrice: 10,
            totalPrice: 100,
            gstRate: 18,
          },
        ],
        subtotal: 660,
        total: 660,
        paymentMethod: "cash",
        paymentStatus: "paid",
        amountPaid: 660,
        balanceDue: 0,
        isInvoiced: false,
      },
      {
        id: "bill_02",
        companyId,
        billNo: "BILL/002",
        customerId: "cust_02",
        customerName: "Priya Traders",
        customerType: "registered",
        date: daysAgo(0),
        items: [
          {
            id: "bi_02_1",
            productId: "brand_dtdc_01",
            productType: "courier_awb",
            productName: "D100001",
            description: `Ravi Shankar - 600006 - 0.450 kg - ${daysAgo(0)}`,
            quantity: 1,
            unit: "Shipment",
            awbSerial: "D100001",
            serviceMode: "Air",
            brandName: "DTDC",
            unitPrice: 95,
            totalPrice: 95,
            gstRate: 18,
            senderName: "Priya Traders",
            senderPhone: "9876500002",
            senderAddress: "78 Commercial Street, Chennai - 600003",
            receiverName: "Ravi Shankar",
            receiverPhone: "9988776655",
            receiverAddress: "14 MG Road, Bangalore - 560001",
            receiverPincode: "560001",
            actualWeightKg: 0.45,
            chargeableWeightKg: 0.45,
          },
          {
            id: "bi_02_2",
            productId: "brand_dtdc_01",
            productType: "courier_awb",
            productName: "D100002",
            description: `Nalini Devi - 600100 - 0.250 kg - ${daysAgo(0)}`,
            quantity: 1,
            unit: "Shipment",
            awbSerial: "D100002",
            serviceMode: "Surface",
            brandName: "DTDC",
            unitPrice: 75,
            totalPrice: 75,
            gstRate: 18,
            senderName: "Priya Traders",
            senderPhone: "9876500002",
            receiverName: "Nalini Devi",
            receiverPhone: "9922334455",
            receiverAddress: "99 Coimbatore Main Road - 641001",
            receiverPincode: "641001",
            actualWeightKg: 0.25,
            chargeableWeightKg: 0.25,
          },
        ],
        subtotal: 170,
        total: 170,
        paymentMethod: "upi",
        paymentStatus: "paid",
        amountPaid: 170,
        balanceDue: 0,
        isInvoiced: false,
      },
      {
        id: "bill_03",
        companyId,
        billNo: "BILL/003",
        customerId: "cust_03",
        customerName: "Suresh Electronics",
        customerType: "registered",
        date: daysAgo(0),
        items: [
          {
            id: "bi_03_1",
            productId: "prod_ink_01",
            productType: "general",
            productName: "Blue Ink Cartridge",
            quantity: 2,
            unit: "Piece",
            unitPrice: 480,
            totalPrice: 960,
            gstRate: 18,
          },
          {
            id: "bi_03_2",
            productId: "prod_xerox_01",
            productType: "xerox",
            productName: "Xerox A4",
            quantity: 50,
            unit: "Page",
            unitPrice: 1.0,
            totalPrice: 50,
            gstRate: 18,
          },
        ],
        subtotal: 1010,
        total: 1010,
        paymentMethod: "credit",
        paymentStatus: "pending",
        amountPaid: 0,
        balanceDue: 1010,
        isInvoiced: false,
      },
      // Yesterday's bills
      {
        id: "bill_04",
        companyId,
        billNo: "BILL/004",
        customerId: "cust_04",
        customerName: "Meena Fashions",
        customerType: "registered",
        date: daysAgo(1),
        items: [
          {
            id: "bi_04_1",
            productId: "brand_bluedart_01",
            productType: "courier_awb",
            productName: "48064699185",
            description: `Sunita Aggarwal - 110001 - 0.500 kg - ${daysAgo(1)}`,
            quantity: 1,
            unit: "Shipment",
            awbSerial: "48064699185",
            serviceMode: "Air",
            brandName: "BlueDart",
            unitPrice: 150,
            totalPrice: 150,
            gstRate: 18,
            senderName: "Meena Fashions",
            senderPhone: "9876500004",
            receiverName: "Sunita Aggarwal",
            receiverPhone: "9811223344",
            receiverAddress: "Block 5, Connaught Place, New Delhi - 110001",
            receiverPincode: "110001",
            actualWeightKg: 0.5,
            chargeableWeightKg: 0.5,
          },
          {
            id: "bi_04_2",
            productId: "prod_bubble_01",
            productType: "general",
            productName: "Bubble Wrap Roll",
            quantity: 1,
            unit: "Roll",
            unitPrice: 350,
            totalPrice: 350,
            gstRate: 18,
          },
        ],
        subtotal: 500,
        total: 500,
        paymentMethod: "upi",
        paymentStatus: "paid",
        amountPaid: 500,
        balanceDue: 0,
        isInvoiced: false,
      },
      {
        id: "bill_05",
        companyId,
        billNo: "BILL/005",
        customerId: "cust_05",
        customerName: "Arjun Logistics",
        customerType: "registered",
        date: daysAgo(1),
        items: [
          {
            id: "bi_05_1",
            productId: "brand_dtdc_01",
            productType: "courier_awb",
            productName: "D100003",
            description: `Kartik Mehta - 400001 - 1.200 kg - ${daysAgo(1)}`,
            quantity: 1,
            unit: "Shipment",
            awbSerial: "D100003",
            serviceMode: "Air",
            brandName: "DTDC",
            unitPrice: 180,
            totalPrice: 180,
            gstRate: 18,
            senderName: "Arjun Logistics",
            senderPhone: "9876500005",
            receiverName: "Kartik Mehta",
            receiverPhone: "9833445566",
            receiverAddress: "Mumbai Central, Mumbai - 400001",
            receiverPincode: "400001",
            actualWeightKg: 1.2,
            chargeableWeightKg: 1.2,
          },
          {
            id: "bi_05_2",
            productId: "brand_dtdc_01",
            productType: "courier_awb",
            productName: "D100004",
            description: `Ranjit Singh - 400002 - 0.800 kg - ${daysAgo(1)}`,
            quantity: 1,
            unit: "Shipment",
            awbSerial: "D100004",
            serviceMode: "Air",
            brandName: "DTDC",
            unitPrice: 140,
            totalPrice: 140,
            gstRate: 18,
            senderName: "Arjun Logistics",
            senderPhone: "9876500005",
            receiverName: "Ranjit Singh",
            receiverPhone: "9877665544",
            receiverAddress: "Dadar West, Mumbai - 400028",
            receiverPincode: "400028",
            actualWeightKg: 0.8,
            chargeableWeightKg: 0.8,
          },
          {
            id: "bi_05_3",
            productId: "prod_tape_01",
            productType: "general",
            productName: "Packing Tape 2 inch",
            quantity: 3,
            unit: "Piece",
            unitPrice: 45,
            totalPrice: 135,
            gstRate: 18,
          },
        ],
        subtotal: 455,
        total: 455,
        paymentMethod: "credit",
        paymentStatus: "partial",
        amountPaid: 300,
        balanceDue: 155,
        isInvoiced: false,
      },
      // 3 days ago
      {
        id: "bill_06",
        companyId,
        billNo: "BILL/006",
        customerId: "cust_06",
        customerName: "Kavitha Pharma",
        customerType: "registered",
        date: daysAgo(3),
        items: [
          {
            id: "bi_06_1",
            productId: "prod_paper_01",
            productType: "general",
            productName: "A4 Paper",
            quantity: 5,
            unit: "Ream",
            unitPrice: 280,
            totalPrice: 1400,
            gstRate: 12,
          },
          {
            id: "bi_06_2",
            productId: "prod_print_01",
            productType: "service",
            productName: "Color Printout",
            description: "Brochure printing 30 pages",
            quantity: 30,
            unit: "Page",
            unitPrice: 15,
            totalPrice: 450,
            gstRate: 18,
          },
          {
            id: "bi_06_3",
            productId: "prod_lam_01",
            productType: "service",
            productName: "Lamination A4",
            description: "Lamination for 10 sheets",
            quantity: 10,
            unit: "Sheet",
            unitPrice: 20,
            totalPrice: 200,
            gstRate: 18,
          },
        ],
        subtotal: 2050,
        total: 2050,
        paymentMethod: "cash",
        paymentStatus: "paid",
        amountPaid: 2050,
        balanceDue: 0,
        isInvoiced: true,
        invoiceId: "inv_01",
      },
      {
        id: "bill_07",
        companyId,
        billNo: "BILL/007",
        customerId: "cust_07",
        customerName: "Sri Balaji Traders",
        customerType: "registered",
        date: daysAgo(3),
        items: [
          {
            id: "bi_07_1",
            productId: "brand_delhivery_01",
            productType: "courier_awb",
            productName: "DL20001",
            description: `Venkat Rao - 500001 - 0.600 kg - ${daysAgo(3)}`,
            quantity: 1,
            unit: "Shipment",
            awbSerial: "DL20001",
            serviceMode: "Surface",
            brandName: "Delhivery",
            unitPrice: 85,
            totalPrice: 85,
            gstRate: 18,
            senderName: "Sri Balaji Traders",
            senderPhone: "9876500007",
            receiverName: "Venkat Rao",
            receiverPhone: "9900112233",
            receiverAddress: "Banjara Hills, Hyderabad - 500034",
            receiverPincode: "500034",
            actualWeightKg: 0.6,
            chargeableWeightKg: 0.6,
          },
        ],
        subtotal: 85,
        total: 85,
        paymentMethod: "cash",
        paymentStatus: "paid",
        amountPaid: 85,
        balanceDue: 0,
        isInvoiced: false,
      },
      // 5 days ago
      {
        id: "bill_08",
        companyId,
        billNo: "BILL/008",
        customerId: "cust_01",
        customerName: "Rajesh Kumar",
        customerType: "registered",
        date: daysAgo(5),
        items: [
          {
            id: "bi_08_1",
            productId: "brand_dtdc_01",
            productType: "courier_awb",
            productName: "D100005",
            description: `Amit Sharma - 302001 - 2.500 kg - ${daysAgo(5)}`,
            quantity: 1,
            unit: "Shipment",
            awbSerial: "D100005",
            serviceMode: "Surface",
            brandName: "DTDC",
            unitPrice: 220,
            totalPrice: 220,
            gstRate: 18,
            senderName: "Rajesh Kumar",
            senderPhone: "9876500001",
            receiverName: "Amit Sharma",
            receiverPhone: "9811001122",
            receiverAddress: "Sindhi Colony, Jaipur - 302001",
            receiverPincode: "302001",
            actualWeightKg: 2.5,
            chargeableWeightKg: 2.5,
          },
          {
            id: "bi_08_2",
            productId: "prod_env_01",
            productType: "general",
            productName: "A4 Envelope",
            quantity: 2,
            unit: "Pack",
            unitPrice: 120,
            totalPrice: 240,
            gstRate: 12,
          },
        ],
        subtotal: 460,
        total: 460,
        paymentMethod: "cash",
        paymentStatus: "paid",
        amountPaid: 460,
        balanceDue: 0,
        isInvoiced: false,
      },
      // 7 days ago
      {
        id: "bill_09",
        companyId,
        billNo: "BILL/009",
        customerId: "cust_02",
        customerName: "Priya Traders",
        customerType: "registered",
        date: daysAgo(7),
        items: [
          {
            id: "bi_09_1",
            productId: "brand_bluedart_01",
            productType: "courier_awb",
            productName: "48064699196",
            description: `Pooja Nair - 682001 - 0.300 kg - ${daysAgo(7)}`,
            quantity: 1,
            unit: "Shipment",
            awbSerial: "48064699196",
            serviceMode: "Air",
            brandName: "BlueDart",
            unitPrice: 130,
            totalPrice: 130,
            gstRate: 18,
            senderName: "Priya Traders",
            senderPhone: "9876500002",
            receiverName: "Pooja Nair",
            receiverPhone: "9944556677",
            receiverAddress: "MG Road, Kochi - 682001",
            receiverPincode: "682001",
            actualWeightKg: 0.3,
            chargeableWeightKg: 0.3,
          },
          {
            id: "bi_09_2",
            productId: "prod_paper_01",
            productType: "general",
            productName: "A4 Paper",
            quantity: 3,
            unit: "Ream",
            unitPrice: 280,
            totalPrice: 840,
            gstRate: 12,
          },
        ],
        subtotal: 970,
        total: 970,
        paymentMethod: "upi",
        paymentStatus: "paid",
        amountPaid: 970,
        balanceDue: 0,
        isInvoiced: true,
        invoiceId: "inv_02",
      },
      // 10 days ago - pending payment
      {
        id: "bill_10",
        companyId,
        billNo: "BILL/010",
        customerId: "cust_05",
        customerName: "Arjun Logistics",
        customerType: "registered",
        date: daysAgo(10),
        items: [
          {
            id: "bi_10_1",
            productId: "brand_dtdc_01",
            productType: "courier_awb",
            productName: "D100006",
            description: `Prakash Iyer - 600097 - 1.800 kg - ${daysAgo(10)}`,
            quantity: 1,
            unit: "Shipment",
            awbSerial: "D100006",
            serviceMode: "Air",
            brandName: "DTDC",
            unitPrice: 200,
            totalPrice: 200,
            gstRate: 18,
            senderName: "Arjun Logistics",
            senderPhone: "9876500005",
            receiverName: "Prakash Iyer",
            receiverPhone: "9855443322",
            receiverAddress: "Sholinganallur, Chennai - 600097",
            receiverPincode: "600097",
            actualWeightKg: 1.8,
            chargeableWeightKg: 1.8,
          },
          {
            id: "bi_10_2",
            productId: "brand_dtdc_01",
            productType: "courier_awb",
            productName: "D100007",
            description: `Deepak Kumar - 600113 - 0.900 kg - ${daysAgo(10)}`,
            quantity: 1,
            unit: "Shipment",
            awbSerial: "D100007",
            serviceMode: "Surface",
            brandName: "DTDC",
            unitPrice: 120,
            totalPrice: 120,
            gstRate: 18,
            senderName: "Arjun Logistics",
            senderPhone: "9876500005",
            receiverName: "Deepak Kumar",
            receiverPhone: "9833221100",
            receiverAddress: "Perumbakkam, Chennai - 600100",
            receiverPincode: "600100",
            actualWeightKg: 0.9,
            chargeableWeightKg: 0.9,
          },
          {
            id: "bi_10_3",
            productId: "prod_bubble_01",
            productType: "general",
            productName: "Bubble Wrap Roll",
            quantity: 2,
            unit: "Roll",
            unitPrice: 350,
            totalPrice: 700,
            gstRate: 18,
          },
        ],
        subtotal: 1020,
        total: 1020,
        paymentMethod: "credit",
        paymentStatus: "pending",
        amountPaid: 0,
        balanceDue: 1020,
        isInvoiced: false,
      },
    ];
    setBills(companyId, bills);

    const settings = getSettings(companyId);
    setSettings(companyId, { ...settings, billSeq: 11 });
  }

  // ─── Invoices ────────────────────────────────────────────────────────────────
  const existingInvoices = getInvoices(companyId);
  if (existingInvoices.length === 0) {
    const invoices: Invoice[] = [
      {
        id: "inv_01",
        companyId,
        invoiceNo: "INV/001",
        invoiceType: "non_gst",
        customerId: "cust_06",
        customerName: "Kavitha Pharma",
        customerAddress: "22 Ambattur Industrial, Chennai - 600058",
        billIds: ["bill_06"],
        date: daysAgo(3),
        items: [
          {
            id: "bi_06_1",
            productId: "prod_paper_01",
            productType: "general",
            productName: "A4 Paper",
            quantity: 5,
            unit: "Ream",
            unitPrice: 280,
            totalPrice: 1400,
            gstRate: 12,
          },
          {
            id: "bi_06_2",
            productId: "prod_print_01",
            productType: "service",
            productName: "Color Printout",
            description: "Brochure printing 30 pages",
            quantity: 30,
            unit: "Page",
            unitPrice: 15,
            totalPrice: 450,
            gstRate: 18,
          },
          {
            id: "bi_06_3",
            productId: "prod_lam_01",
            productType: "service",
            productName: "Lamination A4",
            description: "Lamination for 10 sheets",
            quantity: 10,
            unit: "Sheet",
            unitPrice: 20,
            totalPrice: 200,
            gstRate: 18,
          },
        ],
        subtotal: 2050,
        cgst: 152.5,
        sgst: 152.5,
        igst: 0,
        total: 2355,
        paymentMethod: "cash",
        paymentStatus: "paid",
        createdAt: new Date(Date.now() - 3 * 86400000).toISOString(),
      },
      {
        id: "inv_02",
        companyId,
        invoiceNo: "GST/001",
        invoiceType: "gst",
        customerId: "cust_02",
        customerName: "Priya Traders",
        customerGstin: "33BBBCS5678B1Z5",
        customerAddress: "78 Commercial Street, Chennai - 600003",
        billIds: ["bill_09"],
        date: daysAgo(7),
        items: [
          {
            id: "bi_09_1",
            productId: "brand_bluedart_01",
            productType: "courier_awb",
            productName: "48064699196",
            description: `Pooja Nair - 682001 - 0.300 kg - ${daysAgo(7)}`,
            quantity: 1,
            unit: "Shipment",
            awbSerial: "48064699196",
            serviceMode: "Air",
            brandName: "BlueDart",
            unitPrice: 130,
            totalPrice: 130,
            gstRate: 18,
          },
          {
            id: "bi_09_2",
            productId: "prod_paper_01",
            productType: "general",
            productName: "A4 Paper",
            quantity: 3,
            unit: "Ream",
            unitPrice: 280,
            totalPrice: 840,
            gstRate: 12,
          },
        ],
        subtotal: 970,
        cgst: 80.1,
        sgst: 80.1,
        igst: 0,
        total: 1130.2,
        paymentMethod: "upi",
        paymentStatus: "paid",
        createdAt: new Date(Date.now() - 7 * 86400000).toISOString(),
      },
    ];
    setInvoices(companyId, invoices);
  }

  // ─── Purchase Invoices ───────────────────────────────────────────────────────
  const existingPurchaseInvoices = getPurchaseInvoices(companyId);
  if (existingPurchaseInvoices.length === 0) {
    const purchaseInvoices: PurchaseInvoice[] = [
      {
        id: "pi_01",
        companyId,
        invoiceNo: "PI/001",
        vendorId: "vend_01",
        vendorName: "Chennai Paper Mart",
        date: daysAgo(12),
        items: [
          {
            productId: "prod_paper_01",
            productName: "A4 Paper",
            productType: "general",
            quantity: 50,
            unit: "Ream",
            unitPrice: 220,
            gstRate: 12,
            totalPrice: 12320,
          },
          {
            productId: "prod_env_01",
            productName: "A4 Envelope",
            productType: "general",
            quantity: 20,
            unit: "Pack",
            unitPrice: 80,
            gstRate: 12,
            totalPrice: 1792,
          },
        ],
        subtotal: 12600,
        gstAmount: 1512,
        total: 14112,
        paymentStatus: "paid",
      },
      {
        id: "pi_02",
        companyId,
        invoiceNo: "PI/002",
        vendorId: "vend_02",
        vendorName: "DTDC Franchise Hub",
        date: daysAgo(10),
        items: [
          {
            productId: "brand_dtdc_01",
            productName: "DTDC AWB D100001-D100200",
            productType: "courier_awb",
            quantity: 200,
            unit: "Piece",
            unitPrice: 8,
            gstRate: 18,
            totalPrice: 1888,
            awbFrom: "D100001",
            awbTo: "D100200",
          },
        ],
        subtotal: 1600,
        gstAmount: 288,
        total: 1888,
        paymentStatus: "paid",
      },
      {
        id: "pi_03",
        companyId,
        invoiceNo: "PI/003",
        vendorId: "vend_05",
        vendorName: "Packcraft Supplies",
        date: daysAgo(8),
        items: [
          {
            productId: "prod_bubble_01",
            productName: "Bubble Wrap Roll",
            productType: "general",
            quantity: 20,
            unit: "Roll",
            unitPrice: 250,
            gstRate: 18,
            totalPrice: 5900,
          },
          {
            productId: "prod_tape_01",
            productName: "Packing Tape 2 inch",
            productType: "general",
            quantity: 100,
            unit: "Piece",
            unitPrice: 30,
            gstRate: 18,
            totalPrice: 3540,
          },
        ],
        subtotal: 8000,
        gstAmount: 1440,
        total: 9440,
        paymentStatus: "pending",
      },
      {
        id: "pi_04",
        companyId,
        invoiceNo: "PI/004",
        vendorId: "vend_03",
        vendorName: "BlueDart Distribution",
        date: daysAgo(15),
        items: [
          {
            productId: "brand_bluedart_01",
            productName: "BlueDart AWB 48064699185-48064699900",
            productType: "courier_awb",
            quantity: 64,
            unit: "Piece",
            unitPrice: 12,
            gstRate: 18,
            totalPrice: 906.24,
            awbFrom: "48064699185",
            awbTo: "48064699900",
          },
        ],
        subtotal: 768,
        gstAmount: 138.24,
        total: 906.24,
        paymentStatus: "paid",
      },
    ];
    setPurchaseInvoices(companyId, purchaseInvoices);
  }

  // ─── Pickups ─────────────────────────────────────────────────────────────────
  const existingPickups = getPickups(companyId);
  if (existingPickups.length === 0) {
    const today = daysAgo(0);
    const tomorrow = new Date(Date.now() + 86400000)
      .toISOString()
      .split("T")[0];
    const pickups: CourierPickup[] = [
      {
        id: "pickup_01",
        companyId,
        courierBrand: "DTDC",
        scheduledDate: today,
        scheduledTime: "14:00",
        estimatedPieces: 15,
        estimatedBoxes: 3,
        status: "pending",
        notes: "Regular daily pickup - 2 fragile parcels",
      },
      {
        id: "pickup_02",
        companyId,
        courierBrand: "BlueDart",
        scheduledDate: today,
        scheduledTime: "16:30",
        estimatedPieces: 8,
        estimatedBoxes: 2,
        status: "pending",
        notes: "Priority Air shipments only",
      },
      {
        id: "pickup_03",
        companyId,
        courierBrand: "Delhivery",
        scheduledDate: tomorrow,
        scheduledTime: "10:00",
        estimatedPieces: 20,
        estimatedBoxes: 4,
        status: "pending",
      },
      {
        id: "pickup_04",
        companyId,
        courierBrand: "DTDC",
        scheduledDate: daysAgo(1),
        scheduledTime: "14:00",
        estimatedPieces: 12,
        estimatedBoxes: 2,
        status: "confirmed",
        confirmedPieces: 11,
        confirmedBoxes: 2,
        confirmedAt: new Date(Date.now() - 86400000).toISOString(),
        notes: "Confirmed by Mr. Kumar",
      },
    ];
    setPickups(companyId, pickups);
  }

  // ─── Expenses ────────────────────────────────────────────────────────────────
  const existingExpenses = getExpenses(companyId);
  if (existingExpenses.length === 0) {
    const expenses: Expense[] = [
      {
        id: "exp_01",
        companyId,
        date: daysAgo(0),
        category: "Utilities",
        description: "Electricity bill - March",
        amount: 3200,
        notes: "TNEB bill for the month",
      },
      {
        id: "exp_02",
        companyId,
        date: daysAgo(2),
        category: "Salary",
        description: "Staff salary - Feb",
        amount: 28000,
        notes: "2 staff members",
      },
      {
        id: "exp_03",
        companyId,
        date: daysAgo(3),
        category: "Rent",
        description: "Office rent - March",
        amount: 15000,
        notes: "Paid to landlord",
      },
      {
        id: "exp_04",
        companyId,
        date: daysAgo(5),
        category: "Stationery",
        description: "Printer maintenance",
        amount: 1200,
        notes: "Drum replacement",
      },
      {
        id: "exp_05",
        companyId,
        date: daysAgo(7),
        category: "Transport",
        description: "Delivery vehicle fuel",
        amount: 800,
      },
      {
        id: "exp_06",
        companyId,
        date: daysAgo(10),
        category: "Courier",
        description: "Incoming courier charges",
        amount: 450,
        notes: "Return shipments",
      },
      {
        id: "exp_07",
        companyId,
        date: daysAgo(12),
        category: "Misc",
        description: "Office supplies",
        amount: 650,
        notes: "Pens, folders, staples",
      },
      {
        id: "exp_08",
        companyId,
        date: daysAgo(15),
        category: "Maintenance",
        description: "AC servicing",
        amount: 2500,
        notes: "Annual maintenance",
      },
      {
        id: "exp_09",
        companyId,
        date: daysAgo(18),
        category: "Utilities",
        description: "Internet bill - Feb",
        amount: 1499,
        notes: "Airtel broadband",
      },
      {
        id: "exp_10",
        companyId,
        date: daysAgo(30),
        category: "Salary",
        description: "Staff salary - Jan",
        amount: 28000,
        notes: "2 staff members",
      },
      {
        id: "exp_11",
        companyId,
        date: daysAgo(30),
        category: "Rent",
        description: "Office rent - Feb",
        amount: 15000,
      },
      {
        id: "exp_12",
        companyId,
        date: daysAgo(32),
        category: "Transport",
        description: "Delivery van service",
        amount: 1800,
        notes: "Monthly vehicle check",
      },
    ];
    setExpenses(companyId, expenses);
  }

  // ─── Tariffs (DTDC defaults) ─────────────────────────────────────────────────
  const existingTariffs = getTariffs(companyId);
  if (existingTariffs.length === 0) {
    const dtdcTariffs: CourierTariff[] = [
      // Express - Within City
      {
        id: "tariff_dtdc_exp_city",
        companyId,
        brandId: "brand_dtdc_01",
        brandName: "DTDC",
        productType: "Express",
        zone: "Within City",
        transportMode: "Air",
        tariffKind: "selling",
        pricingMode: "slab",
        slabs: [
          { maxGrams: 100, price: 69 },
          { maxGrams: 250, price: 75 },
          { maxGrams: 500, price: 91 },
          { maxGrams: null, price: 43 },
        ],
        aboveSlabRatePerKg: 86,
        maxWeightKg: 3,
        isGSTInclusive: true,
        isActive: true,
      },
      // Express - Within State
      {
        id: "tariff_dtdc_exp_state",
        companyId,
        brandId: "brand_dtdc_01",
        brandName: "DTDC",
        productType: "Express",
        zone: "Within State",
        transportMode: "Both",
        tariffKind: "selling",
        pricingMode: "slab",
        slabs: [
          { maxGrams: 100, price: 96 },
          { maxGrams: 250, price: 101 },
          { maxGrams: 500, price: 112 },
          { maxGrams: null, price: 59 },
        ],
        aboveSlabRatePerKg: 118,
        maxWeightKg: 3,
        isGSTInclusive: true,
        isActive: true,
      },
      // Express - Within Zone
      {
        id: "tariff_dtdc_exp_zone",
        companyId,
        brandId: "brand_dtdc_01",
        brandName: "DTDC",
        productType: "Express",
        zone: "Within Zone",
        transportMode: "Both",
        tariffKind: "selling",
        pricingMode: "slab",
        slabs: [
          { maxGrams: 100, price: 117 },
          { maxGrams: 250, price: 122 },
          { maxGrams: 500, price: 133 },
          { maxGrams: null, price: 69 },
        ],
        aboveSlabRatePerKg: 138,
        maxWeightKg: 3,
        isGSTInclusive: true,
        isActive: true,
      },
      // Express - Metro
      {
        id: "tariff_dtdc_exp_metro",
        companyId,
        brandId: "brand_dtdc_01",
        brandName: "DTDC",
        productType: "Express",
        zone: "Metro Cities",
        transportMode: "Air",
        tariffKind: "selling",
        pricingMode: "slab",
        slabs: [
          { maxGrams: 100, price: 133 },
          { maxGrams: 250, price: 138 },
          { maxGrams: 500, price: 191 },
          { maxGrams: null, price: 128 },
        ],
        aboveSlabRatePerKg: 256,
        maxWeightKg: 5,
        isGSTInclusive: true,
        isActive: true,
      },
      // Express - Rest of India
      {
        id: "tariff_dtdc_exp_roi",
        companyId,
        brandId: "brand_dtdc_01",
        brandName: "DTDC",
        productType: "Express",
        zone: "Rest of India",
        transportMode: "Both",
        tariffKind: "selling",
        pricingMode: "slab",
        slabs: [
          { maxGrams: 100, price: 154 },
          { maxGrams: 250, price: 159 },
          { maxGrams: 500, price: 212 },
          { maxGrams: null, price: 149 },
        ],
        aboveSlabRatePerKg: 298,
        maxWeightKg: 5,
        isGSTInclusive: true,
        isActive: true,
      },
      // Express - Special Destinations
      {
        id: "tariff_dtdc_exp_special",
        companyId,
        brandId: "brand_dtdc_01",
        brandName: "DTDC",
        productType: "Express",
        zone: "Special Destinations",
        transportMode: "Air",
        tariffKind: "selling",
        pricingMode: "slab",
        slabs: [
          { maxGrams: 100, price: 64 },
          { maxGrams: 250, price: 69 },
          { maxGrams: 500, price: 69 },
          { maxGrams: null, price: 48 },
        ],
        aboveSlabRatePerKg: 96,
        maxWeightKg: 5,
        isGSTInclusive: true,
        isActive: true,
      },
      // Cargo Air - Within State
      {
        id: "tariff_dtdc_cargo_air_state",
        companyId,
        brandId: "brand_dtdc_01",
        brandName: "DTDC",
        productType: "Cargo Air",
        zone: "Within State",
        transportMode: "Air",
        tariffKind: "selling",
        pricingMode: "per_kg",
        minKg: 3,
        ratePerKg: 42,
        isGSTInclusive: true,
        isActive: true,
      },
      // Cargo Air - Metro
      {
        id: "tariff_dtdc_cargo_air_metro",
        companyId,
        brandId: "brand_dtdc_01",
        brandName: "DTDC",
        productType: "Cargo Air",
        zone: "Metro Cities",
        transportMode: "Air",
        tariffKind: "selling",
        pricingMode: "per_kg",
        minKg: 3,
        ratePerKg: 55,
        isGSTInclusive: true,
        isActive: true,
      },
      // Cargo Air - Rest of India
      {
        id: "tariff_dtdc_cargo_air_roi",
        companyId,
        brandId: "brand_dtdc_01",
        brandName: "DTDC",
        productType: "Cargo Air",
        zone: "Rest of India",
        transportMode: "Air",
        tariffKind: "selling",
        pricingMode: "per_kg",
        minKg: 3,
        ratePerKg: 62,
        isGSTInclusive: true,
        isActive: true,
      },
      // Cargo Surface - Within City
      {
        id: "tariff_dtdc_cargo_surf_city",
        companyId,
        brandId: "brand_dtdc_01",
        brandName: "DTDC",
        productType: "Cargo Surface",
        zone: "Within City",
        transportMode: "Surface",
        tariffKind: "selling",
        pricingMode: "per_kg",
        minKg: 3,
        ratePerKg: 22,
        isGSTInclusive: true,
        isActive: true,
      },
      // Cargo Surface - Within State
      {
        id: "tariff_dtdc_cargo_surf_state",
        companyId,
        brandId: "brand_dtdc_01",
        brandName: "DTDC",
        productType: "Cargo Surface",
        zone: "Within State",
        transportMode: "Surface",
        tariffKind: "selling",
        pricingMode: "per_kg",
        minKg: 3,
        ratePerKg: 28,
        isGSTInclusive: true,
        isActive: true,
      },
      // Cargo Surface - Rest of India
      {
        id: "tariff_dtdc_cargo_surf_roi",
        companyId,
        brandId: "brand_dtdc_01",
        brandName: "DTDC",
        productType: "Cargo Surface",
        zone: "Rest of India",
        transportMode: "Surface",
        tariffKind: "selling",
        pricingMode: "per_kg",
        minKg: 5,
        ratePerKg: 38,
        isGSTInclusive: true,
        isActive: true,
      },
    ];
    setTariffs(companyId, dtdcTariffs);
  }

  // ─── Design Pricing ─────────────────────────────────────────────────────────
  const existingDesignPricing = getDesignPricing(companyId);
  if (existingDesignPricing.length === 0) {
    const designPricing: DesignPricingMaster[] = [
      {
        id: "dp_01",
        companyId,
        serviceName: "ID Card - Single Side",
        designType: "id_card",
        unit: "per piece",
        basePrice: 25,
        gstRate: 18,
        isActive: true,
      },
      {
        id: "dp_02",
        companyId,
        serviceName: "ID Card - Double Side",
        designType: "id_card",
        unit: "per piece",
        basePrice: 40,
        gstRate: 18,
        isActive: true,
      },
      {
        id: "dp_03",
        companyId,
        serviceName: "Visiting Card (100 pcs)",
        designType: "visiting_card",
        unit: "per set",
        basePrice: 500,
        gstRate: 18,
        isActive: true,
      },
      {
        id: "dp_04",
        companyId,
        serviceName: "Passport Photo (4/sheet)",
        designType: "passport_photo",
        unit: "per sheet",
        basePrice: 60,
        gstRate: 18,
        isActive: true,
      },
      {
        id: "dp_05",
        companyId,
        serviceName: "Stamp Photo (9/sheet)",
        designType: "stamp_photo",
        unit: "per sheet",
        basePrice: 50,
        gstRate: 18,
        isActive: true,
      },
      {
        id: "dp_06",
        companyId,
        serviceName: "Banner Print",
        designType: "banner",
        unit: "per sqft",
        basePrice: 40,
        gstRate: 18,
        isActive: true,
      },
      {
        id: "dp_07",
        companyId,
        serviceName: "Letterhead (500 pcs)",
        designType: "letterhead",
        unit: "per set",
        basePrice: 800,
        gstRate: 18,
        isActive: true,
      },
      {
        id: "dp_08",
        companyId,
        serviceName: "Certificate Print",
        designType: "certificate",
        unit: "per piece",
        basePrice: 30,
        gstRate: 18,
        isActive: true,
      },
      {
        id: "dp_09",
        companyId,
        serviceName: "Custom Design",
        designType: "custom",
        unit: "per piece",
        basePrice: 200,
        gstRate: 18,
        isActive: true,
      },
    ];
    setDesignPricing(companyId, designPricing);
  }

  // ─── Design Orders ───────────────────────────────────────────────────────────
  const existingDesignOrders = getDesignOrders(companyId);
  if (existingDesignOrders.length === 0) {
    const designOrders: DesignOrder[] = [
      {
        id: "do_01",
        companyId,
        orderNo: "DS001",
        date: daysAgo(2),
        customerId: "cust_01",
        customerName: "Rajesh Kumar",
        customerPhone: "9876500001",
        designType: "id_card",
        subType: "Double Sided",
        quantity: 50,
        material: "PVC Card",
        lamination: "Gloss",
        colorMode: "Color",
        designSource: "Customer File",
        specialInstructions:
          "Company logo on front, designation on back. Font: Arial Bold.",
        deliveryDate: daysAgo(-2),
        price: 2000,
        gstIncluded: true,
        gstRate: 18,
        advancePaid: 1000,
        status: "designing",
        createdAt: new Date(Date.now() - 2 * 86400000).toISOString(),
        updatedAt: new Date(Date.now() - 2 * 86400000).toISOString(),
      },
      {
        id: "do_02",
        companyId,
        orderNo: "DS002",
        date: daysAgo(3),
        customerId: "cust_02",
        customerName: "Priya Traders",
        customerPhone: "9876500002",
        designType: "visiting_card",
        subType: "Standard (90×55mm)",
        quantity: 100,
        material: "Art Card 300gsm",
        lamination: "Gloss",
        colorMode: "Color",
        designSource: "We Design",
        specialInstructions:
          "Business card for MD. Gold foil on logo. Both sides.",
        deliveryDate: daysAgo(-1),
        price: 500,
        gstIncluded: true,
        gstRate: 18,
        advancePaid: 500,
        status: "ready_print",
        createdAt: new Date(Date.now() - 3 * 86400000).toISOString(),
        updatedAt: new Date(Date.now() - 1 * 86400000).toISOString(),
      },
      {
        id: "do_03",
        companyId,
        orderNo: "DS003",
        date: daysAgo(0),
        customerName: "Anand Kumar",
        customerPhone: "9876543210",
        designType: "passport_photo",
        subType: "4 per sheet",
        quantity: 5,
        material: "Photo Paper Glossy",
        lamination: "None",
        colorMode: "Color",
        designSource: "Customer File",
        specialInstructions: "White background. Size 35x45mm. 20 photos total.",
        deliveryDate: daysAgo(0),
        price: 300,
        gstIncluded: true,
        gstRate: 18,
        advancePaid: 300,
        status: "pending",
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: "do_04",
        companyId,
        orderNo: "DS004",
        date: daysAgo(5),
        customerId: "cust_03",
        customerName: "Suresh Electronics",
        customerPhone: "9876500003",
        designType: "banner",
        subType: "Custom Size",
        quantity: 1,
        material: "Canvas",
        lamination: "None",
        colorMode: "Color",
        designSource: "Customer File",
        specialInstructions: "6ft x 3ft. Outdoor banner. Flex print.",
        deliveryDate: daysAgo(-3),
        price: 720,
        gstIncluded: true,
        gstRate: 18,
        advancePaid: 720,
        status: "completed",
        createdAt: new Date(Date.now() - 5 * 86400000).toISOString(),
        updatedAt: new Date(Date.now() - 2 * 86400000).toISOString(),
      },
    ];
    setDesignOrders(companyId, designOrders);
  }
};
