/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const CustomerId = IDL.Text;
export const ProductId = IDL.Text;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PickupId = IDL.Text;
export const BillId = IDL.Text;
export const InvoiceId = IDL.Text;
export const VendorId = IDL.Text;
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'currentCompanyId' : IDL.Opt(IDL.Text),
});
export const Customer = IDL.Record({
  'id' : CustomerId,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const Product = IDL.Record({
  'id' : ProductId,
  'name' : IDL.Text,
  'stock' : IDL.Nat,
  'category' : IDL.Text,
  'price' : IDL.Nat,
});
export const InventoryItem = IDL.Record({
  'id' : ProductId,
  'quantity' : IDL.Nat,
  'product' : Product,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCustomer' : IDL.Func([CustomerId, IDL.Text, IDL.Text, IDL.Text], [], []),
  'addProduct' : IDL.Func(
      [ProductId, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
      [],
      [],
    ),
  'addToInventory' : IDL.Func([ProductId, IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'confirmPickup' : IDL.Func([PickupId], [], []),
  'createBill' : IDL.Func(
      [BillId, CustomerId, IDL.Vec(ProductId), IDL.Nat],
      [],
      [],
    ),
  'createInvoice' : IDL.Func(
      [InvoiceId, IDL.Vec(BillId), IDL.Nat, IDL.Bool],
      [],
      [],
    ),
  'createPickup' : IDL.Func(
      [PickupId, VendorId, IDL.Vec(ProductId), IDL.Bool],
      [],
      [],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
  'getInventoryItems' : IDL.Func([], [IDL.Vec(InventoryItem)], ['query']),
  'getProduct' : IDL.Func([ProductId], [IDL.Opt(Product)], ['query']),
  'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'processReturn' : IDL.Func([BillId, IDL.Vec(ProductId)], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const CustomerId = IDL.Text;
  const ProductId = IDL.Text;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PickupId = IDL.Text;
  const BillId = IDL.Text;
  const InvoiceId = IDL.Text;
  const VendorId = IDL.Text;
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'currentCompanyId' : IDL.Opt(IDL.Text),
  });
  const Customer = IDL.Record({
    'id' : CustomerId,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Product = IDL.Record({
    'id' : ProductId,
    'name' : IDL.Text,
    'stock' : IDL.Nat,
    'category' : IDL.Text,
    'price' : IDL.Nat,
  });
  const InventoryItem = IDL.Record({
    'id' : ProductId,
    'quantity' : IDL.Nat,
    'product' : Product,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCustomer' : IDL.Func(
        [CustomerId, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'addProduct' : IDL.Func(
        [ProductId, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
        [],
        [],
      ),
    'addToInventory' : IDL.Func([ProductId, IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'confirmPickup' : IDL.Func([PickupId], [], []),
    'createBill' : IDL.Func(
        [BillId, CustomerId, IDL.Vec(ProductId), IDL.Nat],
        [],
        [],
      ),
    'createInvoice' : IDL.Func(
        [InvoiceId, IDL.Vec(BillId), IDL.Nat, IDL.Bool],
        [],
        [],
      ),
    'createPickup' : IDL.Func(
        [PickupId, VendorId, IDL.Vec(ProductId), IDL.Bool],
        [],
        [],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
    'getInventoryItems' : IDL.Func([], [IDL.Vec(InventoryItem)], ['query']),
    'getProduct' : IDL.Func([ProductId], [IDL.Opt(Product)], ['query']),
    'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'processReturn' : IDL.Func([BillId, IDL.Vec(ProductId)], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };